services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - ${PWD}/src:/app/src
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
